### ISSUE TITLE
SDL 2 branch merged into pygame. Now consider joining pygame?

### ISSUE THREAD

**Issue by illume** [renpy/pygame_sdl2#109]
Hello,

the SDL2 branch has been merged into pygame now. There are still several open issues (like there is no cdrom module in SDL2), but already most of the existing pygame API works.

Soon we will be moving to continuous releases (pygame 2.0.0.devX to be released to pypi automatically after every PR is merged). Which should address your concern of not having to wait for pygame releases to fix issues. The option of forking for emergency fixes also exists.

Happy to look into help adding things which renpy needs in order to use pygame.

If you're still not interested, please excuse the interruption.

**Comment by renpytom** [comment]
While I like the idea, I have Ren'Py working well on the pygame_sdl2 codebase, with people regularly releasing to Android and iOS. I think kind of undoing that to work on a version of pygame probably wouldn't be the best use of my time, especially since I'd need to see that the maintenance that's been going on lately keeps up for a few years. 

What I'm thinking about is - at some point - renaming pygame_sdl2 to something else, to make sure it's Ren'Py specific, and then taking a wait-and-see approach to decide if there's a compelling reason to merge back in.

**Comment by illume** [comment]
Ok, no worries. Sorry for the interruption then.

Oh, that would be wonderful if you could rename it! It's sort of annoying having to keep telling people it's not pygame when it doesn't work for them.

How are you releasing LGPL stuff to iOS legally? pygame_sdl2 is obviously a derivative work since you used the pygame source code. Is there some sort of way to do this now? I was hoping to do a big license change effort and assign the copyright to the Python Software Foundation... but it sounds like if iOS can take LGPL code somehow we might not need to go through with the license change effort (but moving to under the PSF is useful).

**Comment by renpytom** [comment]
I'll take care of this when I get some chances - I've been busy lately, but things are calming down. 

I've been distributing Ren'Py under LGPL section 6c, which says that you can distribute it along with a written offer to provide the source code required to create the executables. Since Ren'Py has a reasonably strong distinction between the engine and game scripts, the user can then combine the game data from an iOS backup with the newly-linked Ren'Py to get a package they can install through xcode.

I suspect the same approach would work with just about any Pygame program.
